

--공지사항(border) table

CREATE TABLE BORDER (
BORDER_ID NUMBER PRIMARY KEY,
BORDER_WRITER VARCHAR2(50),
BORDER_DATE DATE,
BORDER_TITLE VARCHAR2(200),
BORDER_CONTENT VARCHAR2(4000),
BORDER_HIT NUMBER);


create table users (
	user_no        number          primary key,
	user_id        varchar2(100)   not null,
	user_password  varchar2(512)   not null,
	user_name      varchar2(50)    not null,
	user_alias     varchar2(50),
	user_address   varchar2(300),
	user_tel	   varchar2(100),
	user_subscribe number          default 0,
	user_author    varchar2(50)    default 'user'
	
);

create sequence userno_seq
start with 1
increment by 1
nomaxvalue
nominvalue;


-- notice(커뮤니티)

CREATE TABLE "MICOL"."COMMUNITY" 
   (   "COMM_NO" NUMBER NOT NULL ENABLE, 
   "USER_ALIAS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
   "COMM_DATE" DATE NOT NULL ENABLE, 
   "COMM_TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
   "COMM_CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
   "COMM_CATEGORY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
   "COMM_IMAGE1" VARCHAR2(500 BYTE), 
   "COMM_IMAGE2" VARCHAR2(500 BYTE), 
   "COMM_IMAGE3" VARCHAR2(500 BYTE), 
   "COMM_HIT" NUMBER NOT NULL ENABLE, 
    CONSTRAINT "COMMUNITY_PK" PRIMARY KEY ("COMM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_NO" IS '게시물번호';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."USER_ALIAS" IS '닉네임';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_DATE" IS '등록날짜';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_TITLE" IS '제목';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_CONTENT" IS '내용';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_IMAGE1" IS '이미지1';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_IMAGE2" IS '이미지2';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_IMAGE3" IS '이미지3';
   COMMENT ON COLUMN "MICOL"."COMMUNITY"."COMM_HIT" IS '조회수';

--   공지사항...

   
   
  CREATE TABLE "MICOL"."BORDER" 
   (	"BORDER_ID" NUMBER NOT NULL ENABLE, 
	"BORDER_WRITER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BORDER_DATE" DATE NOT NULL ENABLE, 
	"BORDER_TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"BORDER_CONTENTS" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"BORDER_HIT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_ID" IS '순번';
   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_WRITER" IS '작성자';
   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_DATE" IS '날짜';
   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_TITLE" IS '제목';
   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_CONTENTS" IS '내용';
   COMMENT ON COLUMN "MICOL"."BORDER"."BORDER_HIT" IS '조회수';

   
   
   
   
   
