
--공지사항(border) table

CREATE TABLE BORDER (
BORDER_ID NUMBER PRIMARY KEY,
BORDER_WRITER VARCHAR2(50),
BORDER_DATE DATE,
BORDER_TITLE VARCHAR2(200),
BORDER_CONTENT VARCHAR2(4000),
BORDER_HIT NUMBER);

